server:
  port: 8081
  servlet:
    context-path: /livraria-client-microservice
integrations.resource-server.url: http://localhost:8080/oauth2-resourceserver-livraria

feign:
  client:
    config:
      livroClient:
        loggerLevel: full
      detalhaAutorClient:
        loggerLevel: full
logging.level.br.com.zup.edu.livrariaclient.client.DetalhaLivroClient: DEBUG
logging.level.br.com.zup.edu.livrariaclient.client.DetalhaAutorClient: DEBUG

##
# Client Credentials Flow
##
spring:
  security:
    oauth2:
      client:
        registration:
          exposicao-livros:
            client-id: exposicao-livros-client
            client-secret: yBSwr6WyC3yNkwvLSlCSY953B5MFIKIP
            authorization-grant-type: client_credentials
            #            redirect-uri: "{baseUrl}/authorized/okta"
            scope: livraria:read
        provider:
          exposicao-livros:
            #            authorization-uri: http://localhost:18080/auth/realms/gestao-funcionarios/protocol/openid-connect/auth
            token-uri: http://localhost:18080/auth/realms/livraria/protocol/openid-connect/token
